### ISSUE TITLE
Peer Review #3

### ISSUE THREAD

**Issue by Crooksyyy** [RayanAlim/Analysis-of-Morbidity-in-New-York#3]
# Readme 
Expand on how the data is collected from death certificates, I don't think that is generally available 
Good LLM message
Overall good readme 

# Data 
## analysis data 
extra file need to be removed 

# Scripts 
All files in script file are rmd not an r script - this does not make sense 
## Clean_Raw_data 
I do not believe you obtain the raw data in a reproducible way - may want to include that in readme 
Good job cleaning the data 
## Missing scripts 
no data simulation or testing completed 

## Leading_cause_of_death
This does not need to be its own script and can be in the final qmd file 
well commented 

# Models 
included converted deaths to numeric - this was done in data cleaning 
needs comments for model - why negative binomial 

# Other 
## sketches 
Good sketches of data and graph 
## usage 
remove this file if you did not use an llm 

# Paper 
the paper qmd does not match the paper pdf 
qmd set up is complete
good abstract
not sure the subtitle is needed - what does it convey that the title does not 
authors missing 
unneeded library "library(palmerpenguins)" 
data is not loaded into file 
format data section better - use actual sub-heading not just all caps "DATA" or "Dataset Context and Broader Implications" 
data section appears to be well done just needs formatting 
Otherwise paper appears incomplete and cannot be commented on 

# Overall 
Appears to have aspects of a completed paper but is missing several aspects of a completed paper and a reproducible repo

**Comment by RayanAlim** [comment]
All addressed:
- Expanded on how the data is collected from death certificates
- cleaned up repo and file structure
- Added simulation 
- Added tests
- changed rmd files to R scripts
