### ISSUE TITLE
Peer Review by Emily Su (moonsdust)

### ISSUE THREAD

**Issue by moonsdust** [RayanAlim/Analysis-of-Morbidity-in-New-York#5]
# README.md

- LLM usage statement is present, which is great! I also like how you included steps in your README on how someone can get started with reproducing your paper and results.

# Paper

- The paper (at the time of writing this review) isn't rendered with the newest updates in paper.qmd. 
- Excellent start with your abstract! I would recommend making your abstract longer (2 sentences longer) and include details about what you found once you are finished with your analysis.
- When you write your introduction, make sure to state your estimand!
- I know you are not complete the paper but just a general reminder to mention all packages you use and cite R in the Data Section.
- In your data section, measurement section can be longer in terms of how New York City Department of Health and Mental Hygiene collected the data and each entry was entered in the dataset/s.
- For your analysis data, it could be saved as a parquet file instead of a CSV file since on the rubric they are looking for you to save your data as a parquet file.
- Make sure to justify and explain your model throughly once you start writing your models section!

# Scripts

- I noticed that the scripts are in the rmd format. I would recommend using the script format provided in the starter file. This goes the same for the scripts for the models you have written.
- There are scripts missing for simulating and testing the dataset. 
- However, excellent coding style! Your code is commented throughout.

**Comment by RayanAlim** [comment]
All Addressed:
- Cited R 
- Added more info to the measurements section 
- Added model information and justification 
- changed rmd to r scripts
- added simulation and test scripts
